// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: proto/notary_service.proto

// auto gen codes: protoc --go_out=plugins=grpc:. --go_opt=paths=source_relative *.proto

package proto

import (
	context "context"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlockchainTxStatus is used to record blockchain transaction status, once a cross transaction is created notary service should
// start monitoring different blockchain updates and record tx status in BlockchainTxStatus.
type BlockchainTxStatus int32

const (
	BlockchainTxStatus_waitingUserSent BlockchainTxStatus = 0
	BlockchainTxStatus_waitingVConfirm BlockchainTxStatus = 1
	BlockchainTxStatus_vConfirmed      BlockchainTxStatus = 2
	BlockchainTxStatus_waitingUConfirm BlockchainTxStatus = 3
	BlockchainTxStatus_uConfirmed      BlockchainTxStatus = 4
	BlockchainTxStatus_failed          BlockchainTxStatus = 5
)

// Enum value maps for BlockchainTxStatus.
var (
	BlockchainTxStatus_name = map[int32]string{
		0: "waitingUserSent",
		1: "waitingVConfirm",
		2: "vConfirmed",
		3: "waitingUConfirm",
		4: "uConfirmed",
		5: "failed",
	}
	BlockchainTxStatus_value = map[string]int32{
		"waitingUserSent": 0,
		"waitingVConfirm": 1,
		"vConfirmed":      2,
		"waitingUConfirm": 3,
		"uConfirmed":      4,
		"failed":          5,
	}
)

func (x BlockchainTxStatus) Enum() *BlockchainTxStatus {
	p := new(BlockchainTxStatus)
	*p = x
	return p
}

func (x BlockchainTxStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockchainTxStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notary_service_proto_enumTypes[0].Descriptor()
}

func (BlockchainTxStatus) Type() protoreflect.EnumType {
	return &file_proto_notary_service_proto_enumTypes[0]
}

func (x BlockchainTxStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockchainTxStatus.Descriptor instead.
func (BlockchainTxStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{0}
}

// cross transaction ticket status
type TicketStatus int32

const (
	TicketStatus_created  TicketStatus = 0
	TicketStatus_finished TicketStatus = 1
	TicketStatus_txFailed TicketStatus = 2
)

// Enum value maps for TicketStatus.
var (
	TicketStatus_name = map[int32]string{
		0: "created",
		1: "finished",
		2: "txFailed",
	}
	TicketStatus_value = map[string]int32{
		"created":  0,
		"finished": 1,
		"txFailed": 2,
	}
)

func (x TicketStatus) Enum() *TicketStatus {
	p := new(TicketStatus)
	*p = x
	return p
}

func (x TicketStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TicketStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notary_service_proto_enumTypes[1].Descriptor()
}

func (TicketStatus) Type() protoreflect.EnumType {
	return &file_proto_notary_service_proto_enumTypes[1]
}

func (x TicketStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TicketStatus.Descriptor instead.
func (TicketStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{1}
}

type TicketOps int32

const (
	TicketOps_approve TicketOps = 0
	TicketOps_reject  TicketOps = 1
	TicketOps_quite   TicketOps = 2
)

// Enum value maps for TicketOps.
var (
	TicketOps_name = map[int32]string{
		0: "approve",
		1: "reject",
		2: "quite",
	}
	TicketOps_value = map[string]int32{
		"approve": 0,
		"reject":  1,
		"quite":   2,
	}
)

func (x TicketOps) Enum() *TicketOps {
	p := new(TicketOps)
	*p = x
	return p
}

func (x TicketOps) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TicketOps) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notary_service_proto_enumTypes[2].Descriptor()
}

func (TicketOps) Type() protoreflect.EnumType {
	return &file_proto_notary_service_proto_enumTypes[2]
}

func (x TicketOps) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TicketOps.Descriptor instead.
func (TicketOps) EnumDescriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{2}
}

type TransferPropertyRequest_NetworkType int32

const (
	TransferPropertyRequest_eth    TransferPropertyRequest_NetworkType = 0
	TransferPropertyRequest_fabric TransferPropertyRequest_NetworkType = 1
)

// Enum value maps for TransferPropertyRequest_NetworkType.
var (
	TransferPropertyRequest_NetworkType_name = map[int32]string{
		0: "eth",
		1: "fabric",
	}
	TransferPropertyRequest_NetworkType_value = map[string]int32{
		"eth":    0,
		"fabric": 1,
	}
)

func (x TransferPropertyRequest_NetworkType) Enum() *TransferPropertyRequest_NetworkType {
	p := new(TransferPropertyRequest_NetworkType)
	*p = x
	return p
}

func (x TransferPropertyRequest_NetworkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferPropertyRequest_NetworkType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notary_service_proto_enumTypes[3].Descriptor()
}

func (TransferPropertyRequest_NetworkType) Type() protoreflect.EnumType {
	return &file_proto_notary_service_proto_enumTypes[3]
}

func (x TransferPropertyRequest_NetworkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferPropertyRequest_NetworkType.Descriptor instead.
func (TransferPropertyRequest_NetworkType) EnumDescriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{7, 0}
}

// empty message, used to fill in the rpc arguments or return types
type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping string `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{2}
}

// cross chain transaction filled parameters
type CrossTxDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EFrom          string `protobuf:"bytes,1,opt,name=eFrom,proto3" json:"eFrom,omitempty"`
	ETo            string `protobuf:"bytes,2,opt,name=eTo,proto3" json:"eTo,omitempty"`
	EAmount        string `protobuf:"bytes,3,opt,name=eAmount,proto3" json:"eAmount,omitempty"`
	FFrom          string `protobuf:"bytes,4,opt,name=fFrom,proto3" json:"fFrom,omitempty"`
	FTo            string `protobuf:"bytes,5,opt,name=fTo,proto3" json:"fTo,omitempty"`
	FAmount        string `protobuf:"bytes,6,opt,name=fAmount,proto3" json:"fAmount,omitempty"`
	FChannel       string `protobuf:"bytes,7,opt,name=fChannel,proto3" json:"fChannel,omitempty"`
	FChaincodeName string `protobuf:"bytes,8,opt,name=fChaincodeName,proto3" json:"fChaincodeName,omitempty"`
}

func (x *CrossTxDetail) Reset() {
	*x = CrossTxDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrossTxDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossTxDetail) ProtoMessage() {}

func (x *CrossTxDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossTxDetail.ProtoReflect.Descriptor instead.
func (*CrossTxDetail) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{3}
}

func (x *CrossTxDetail) GetEFrom() string {
	if x != nil {
		return x.EFrom
	}
	return ""
}

func (x *CrossTxDetail) GetETo() string {
	if x != nil {
		return x.ETo
	}
	return ""
}

func (x *CrossTxDetail) GetEAmount() string {
	if x != nil {
		return x.EAmount
	}
	return ""
}

func (x *CrossTxDetail) GetFFrom() string {
	if x != nil {
		return x.FFrom
	}
	return ""
}

func (x *CrossTxDetail) GetFTo() string {
	if x != nil {
		return x.FTo
	}
	return ""
}

func (x *CrossTxDetail) GetFAmount() string {
	if x != nil {
		return x.FAmount
	}
	return ""
}

func (x *CrossTxDetail) GetFChannel() string {
	if x != nil {
		return x.FChannel
	}
	return ""
}

func (x *CrossTxDetail) GetFChaincodeName() string {
	if x != nil {
		return x.FChaincodeName
	}
	return ""
}

// error message with error code, set code to none-zero values if error happens
// record error message in errMsg
type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

// Request received from user to specify a cross chain transaction
type CreateCrossTxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Detail *CrossTxDetail `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *CreateCrossTxReq) Reset() {
	*x = CreateCrossTxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCrossTxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCrossTxReq) ProtoMessage() {}

func (x *CreateCrossTxReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCrossTxReq.ProtoReflect.Descriptor instead.
func (*CreateCrossTxReq) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCrossTxReq) GetDetail() *CrossTxDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

// Response send to user or client when a specified request received.
// if error happens, fill error code and error message.
type CreateCrossTxResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error       *Error               `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	CTxId       string               `protobuf:"bytes,2,opt,name=cTxId,proto3" json:"cTxId,omitempty"` //cross transaction id
	VEthAddress string               `protobuf:"bytes,3,opt,name=vEthAddress,proto3" json:"vEthAddress,omitempty"`
	VFabAddress string               `protobuf:"bytes,4,opt,name=vFabAddress,proto3" json:"vFabAddress,omitempty"`
	CreateTime  *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
}

func (x *CreateCrossTxResp) Reset() {
	*x = CreateCrossTxResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCrossTxResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCrossTxResp) ProtoMessage() {}

func (x *CreateCrossTxResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCrossTxResp.ProtoReflect.Descriptor instead.
func (*CreateCrossTxResp) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCrossTxResp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CreateCrossTxResp) GetCTxId() string {
	if x != nil {
		return x.CTxId
	}
	return ""
}

func (x *CreateCrossTxResp) GetVEthAddress() string {
	if x != nil {
		return x.VEthAddress
	}
	return ""
}

func (x *CreateCrossTxResp) GetVFabAddress() string {
	if x != nil {
		return x.VFabAddress
	}
	return ""
}

func (x *CreateCrossTxResp) GetCreateTime() *timestamp.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

// this request is used for users to send tokens to the verifier/notary
// in this request, user should specify the target cross transaction id and network type(ether or fabric)
type TransferPropertyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data        []byte                              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`   // signed ether transaction data
	CTxId       string                              `protobuf:"bytes,2,opt,name=cTxId,proto3" json:"cTxId,omitempty"` // cross transaction id
	NetworkType TransferPropertyRequest_NetworkType `protobuf:"varint,3,opt,name=networkType,proto3,enum=proto.TransferPropertyRequest_NetworkType" json:"networkType,omitempty"`
}

func (x *TransferPropertyRequest) Reset() {
	*x = TransferPropertyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferPropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferPropertyRequest) ProtoMessage() {}

func (x *TransferPropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferPropertyRequest.ProtoReflect.Descriptor instead.
func (*TransferPropertyRequest) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{7}
}

func (x *TransferPropertyRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TransferPropertyRequest) GetCTxId() string {
	if x != nil {
		return x.CTxId
	}
	return ""
}

func (x *TransferPropertyRequest) GetNetworkType() TransferPropertyRequest_NetworkType {
	if x != nil {
		return x.NetworkType
	}
	return TransferPropertyRequest_eth
}

// response of the LockEtherRequest, return ether transaction id or receipt if necessary,
// or return error message if transaction is not valid
type TransferPropertyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error  *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	TxData []byte `protobuf:"bytes,2,opt,name=txData,proto3" json:"txData,omitempty"`
}

func (x *TransferPropertyResponse) Reset() {
	*x = TransferPropertyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferPropertyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferPropertyResponse) ProtoMessage() {}

func (x *TransferPropertyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferPropertyResponse.ProtoReflect.Descriptor instead.
func (*TransferPropertyResponse) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{8}
}

func (x *TransferPropertyResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *TransferPropertyResponse) GetTxData() []byte {
	if x != nil {
		return x.TxData
	}
	return nil
}

// list cross transaction, add filter if necessage
type ListTxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListTxRequest) Reset() {
	*x = ListTxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTxRequest) ProtoMessage() {}

func (x *ListTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTxRequest.ProtoReflect.Descriptor instead.
func (*ListTxRequest) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{9}
}

// EscrowingStatus means ethereum tx execute result, fabric tx execute result is also included.
type EscrowStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EStatus BlockchainTxStatus `protobuf:"varint,1,opt,name=eStatus,proto3,enum=proto.BlockchainTxStatus" json:"eStatus,omitempty"`
	FStatus BlockchainTxStatus `protobuf:"varint,2,opt,name=fStatus,proto3,enum=proto.BlockchainTxStatus" json:"fStatus,omitempty"`
}

func (x *EscrowStatus) Reset() {
	*x = EscrowStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EscrowStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowStatus) ProtoMessage() {}

func (x *EscrowStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowStatus.ProtoReflect.Descriptor instead.
func (*EscrowStatus) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{10}
}

func (x *EscrowStatus) GetEStatus() BlockchainTxStatus {
	if x != nil {
		return x.EStatus
	}
	return BlockchainTxStatus_waitingUserSent
}

func (x *EscrowStatus) GetFStatus() BlockchainTxStatus {
	if x != nil {
		return x.FStatus
	}
	return BlockchainTxStatus_waitingUserSent
}

type CrossTxStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Status:
	//	*CrossTxStatus_TStatus
	//	*CrossTxStatus_EStatus
	Status isCrossTxStatus_Status `protobuf_oneof:"status"`
}

func (x *CrossTxStatus) Reset() {
	*x = CrossTxStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrossTxStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossTxStatus) ProtoMessage() {}

func (x *CrossTxStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossTxStatus.ProtoReflect.Descriptor instead.
func (*CrossTxStatus) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{11}
}

func (m *CrossTxStatus) GetStatus() isCrossTxStatus_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (x *CrossTxStatus) GetTStatus() TicketStatus {
	if x, ok := x.GetStatus().(*CrossTxStatus_TStatus); ok {
		return x.TStatus
	}
	return TicketStatus_created
}

func (x *CrossTxStatus) GetEStatus() *EscrowStatus {
	if x, ok := x.GetStatus().(*CrossTxStatus_EStatus); ok {
		return x.EStatus
	}
	return nil
}

type isCrossTxStatus_Status interface {
	isCrossTxStatus_Status()
}

type CrossTxStatus_TStatus struct {
	TStatus TicketStatus `protobuf:"varint,1,opt,name=tStatus,proto3,enum=proto.TicketStatus,oneof"`
}

type CrossTxStatus_EStatus struct {
	EStatus *EscrowStatus `protobuf:"bytes,2,opt,name=eStatus,proto3,oneof"`
}

func (*CrossTxStatus_TStatus) isCrossTxStatus_Status() {}

func (*CrossTxStatus_EStatus) isCrossTxStatus_Status() {}

// cross transaction ticket info
type CrossTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CTxId          string               `protobuf:"bytes,1,opt,name=cTxId,proto3" json:"cTxId,omitempty"`
	Detail         *CrossTxDetail       `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Status         *CrossTxStatus       `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime     *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	LastUpdateTime *timestamp.Timestamp `protobuf:"bytes,5,opt,name=lastUpdateTime,proto3" json:"lastUpdateTime,omitempty"`
}

func (x *CrossTx) Reset() {
	*x = CrossTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrossTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossTx) ProtoMessage() {}

func (x *CrossTx) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossTx.ProtoReflect.Descriptor instead.
func (*CrossTx) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{12}
}

func (x *CrossTx) GetCTxId() string {
	if x != nil {
		return x.CTxId
	}
	return ""
}

func (x *CrossTx) GetDetail() *CrossTxDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *CrossTx) GetStatus() *CrossTxStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CrossTx) GetCreateTime() *timestamp.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *CrossTx) GetLastUpdateTime() *timestamp.Timestamp {
	if x != nil {
		return x.LastUpdateTime
	}
	return nil
}

// blockchain transaction records
type TxIdsInBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UETid string `protobuf:"bytes,1,opt,name=UETid,proto3" json:"UETid,omitempty"`
	VETid string `protobuf:"bytes,2,opt,name=VETid,proto3" json:"VETid,omitempty"`
	FETid string `protobuf:"bytes,3,opt,name=FETid,proto3" json:"FETid,omitempty"`
	FVTid string `protobuf:"bytes,4,opt,name=FVTid,proto3" json:"FVTid,omitempty"`
}

func (x *TxIdsInBlock) Reset() {
	*x = TxIdsInBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxIdsInBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxIdsInBlock) ProtoMessage() {}

func (x *TxIdsInBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxIdsInBlock.ProtoReflect.Descriptor instead.
func (*TxIdsInBlock) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{13}
}

func (x *TxIdsInBlock) GetUETid() string {
	if x != nil {
		return x.UETid
	}
	return ""
}

func (x *TxIdsInBlock) GetVETid() string {
	if x != nil {
		return x.VETid
	}
	return ""
}

func (x *TxIdsInBlock) GetFETid() string {
	if x != nil {
		return x.FETid
	}
	return ""
}

func (x *TxIdsInBlock) GetFVTid() string {
	if x != nil {
		return x.FVTid
	}
	return ""
}

// list all the cross chain transaction tickets with detail info
// set error message to error if error happens
type ListTxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error  *Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Detail []*CrossTx `protobuf:"bytes,2,rep,name=detail,proto3" json:"detail,omitempty"`
}

func (x *ListTxResponse) Reset() {
	*x = ListTxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTxResponse) ProtoMessage() {}

func (x *ListTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTxResponse.ProtoReflect.Descriptor instead.
func (*ListTxResponse) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListTxResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ListTxResponse) GetDetail() []*CrossTx {
	if x != nil {
		return x.Detail
	}
	return nil
}

// query cross transaction with specified ticket id
type QueryTxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketId string `protobuf:"bytes,1,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
}

func (x *QueryTxRequest) Reset() {
	*x = QueryTxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTxRequest) ProtoMessage() {}

func (x *QueryTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTxRequest.ProtoReflect.Descriptor instead.
func (*QueryTxRequest) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{15}
}

func (x *QueryTxRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

// response to query cross chain transaction ticket with specified ticket id
type QueryTxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error         *Error        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Detail        *CrossTx      `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	BlockchainTxs *TxIdsInBlock `protobuf:"bytes,3,opt,name=blockchainTxs,proto3" json:"blockchainTxs,omitempty"`
}

func (x *QueryTxResponse) Reset() {
	*x = QueryTxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTxResponse) ProtoMessage() {}

func (x *QueryTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTxResponse.ProtoReflect.Descriptor instead.
func (*QueryTxResponse) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{16}
}

func (x *QueryTxResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *QueryTxResponse) GetDetail() *CrossTx {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *QueryTxResponse) GetBlockchainTxs() *TxIdsInBlock {
	if x != nil {
		return x.BlockchainTxs
	}
	return nil
}

// admin approve or reject a cross transaction ticket
type AdminOpTicketReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CTxTicketId string    `protobuf:"bytes,1,opt,name=cTxTicketId,proto3" json:"cTxTicketId,omitempty"`
	Op          TicketOps `protobuf:"varint,2,opt,name=op,proto3,enum=proto.TicketOps" json:"op,omitempty"`
}

func (x *AdminOpTicketReq) Reset() {
	*x = AdminOpTicketReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminOpTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminOpTicketReq) ProtoMessage() {}

func (x *AdminOpTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminOpTicketReq.ProtoReflect.Descriptor instead.
func (*AdminOpTicketReq) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{17}
}

func (x *AdminOpTicketReq) GetCTxTicketId() string {
	if x != nil {
		return x.CTxTicketId
	}
	return ""
}

func (x *AdminOpTicketReq) GetOp() TicketOps {
	if x != nil {
		return x.Op
	}
	return TicketOps_approve
}

// admin operation response, set error code to None-zero if error happens
type AdminOpTicketResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err *Error `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *AdminOpTicketResp) Reset() {
	*x = AdminOpTicketResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notary_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminOpTicketResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminOpTicketResp) ProtoMessage() {}

func (x *AdminOpTicketResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminOpTicketResp.ProtoReflect.Descriptor instead.
func (*AdminOpTicketResp) Descriptor() ([]byte, []int) {
	return file_proto_notary_service_proto_rawDescGZIP(), []int{18}
}

func (x *AdminOpTicketResp) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

var File_proto_notary_service_proto protoreflect.FileDescriptor

var file_proto_notary_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x74, 0x61, 0x72, 0x79, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x22, 0x1a, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0xd7, 0x01, 0x0a, 0x0d, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x54,
	0x78, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x46, 0x72, 0x6f, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x54, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x54, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x46, 0x72,
	0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x46, 0x72, 0x6f, 0x6d, 0x12,
	0x10, 0x0a, 0x03, 0x66, 0x54, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x54,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x66, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x66, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x33, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72,
	0x72, 0x4d, 0x73, 0x67, 0x22, 0x40, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x72,
	0x6f, 0x73, 0x73, 0x54, 0x78, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x54, 0x78, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0xcd, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x54, 0x78, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x54, 0x78, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x45, 0x74, 0x68, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76, 0x45, 0x74,
	0x68, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x46, 0x61, 0x62,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76,
	0x46, 0x61, 0x62, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xb5, 0x01, 0x0a, 0x17, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x54, 0x78, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x54, 0x78, 0x49, 0x64, 0x12, 0x4c, 0x0a, 0x0b,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x22, 0x22, 0x0a, 0x0b, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x65, 0x74, 0x68,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x10, 0x01, 0x22, 0x56,
	0x0a, 0x18, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x78, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x74, 0x78, 0x44, 0x61, 0x74, 0x61, 0x22, 0x0f, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x78,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x78, 0x0a, 0x0c, 0x45, 0x73, 0x63, 0x72, 0x6f,
	0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x33, 0x0a, 0x07, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x78, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x07, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x33, 0x0a, 0x07,
	0x66, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x07, 0x66, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x7b, 0x0a, 0x0d, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x2f, 0x0a, 0x07, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x07, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x2f, 0x0a, 0x07, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x73, 0x63,
	0x72, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x07, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xfb,
	0x01, 0x0a, 0x07, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x54, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x54,
	0x78, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x54, 0x78, 0x49, 0x64,
	0x12, 0x2c, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x54, 0x78,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x2c,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x54, 0x78, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3a, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x6c, 0x61,
	0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x66, 0x0a, 0x0c,
	0x54, 0x78, 0x49, 0x64, 0x73, 0x49, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05,
	0x55, 0x45, 0x54, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x55, 0x45, 0x54,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x45, 0x54, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x56, 0x45, 0x54, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x45, 0x54, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x46, 0x45, 0x54, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x46, 0x56, 0x54, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x46,
	0x56, 0x54, 0x69, 0x64, 0x22, 0x5c, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x78, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x26, 0x0a, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x54, 0x78, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x22, 0x2c, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x78, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64,
	0x22, 0x98, 0x01, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x26, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x54, 0x78, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x12, 0x39, 0x0a, 0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x78,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x54, 0x78, 0x49, 0x64, 0x73, 0x49, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0d, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x78, 0x73, 0x22, 0x56, 0x0a, 0x10, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x4f, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x54, 0x78, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x54, 0x78, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4f, 0x70, 0x73, 0x52,
	0x02, 0x6f, 0x70, 0x22, 0x33, 0x0a, 0x11, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4f, 0x70, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x2a, 0x7f, 0x0a, 0x12, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x13,
	0x0a, 0x0f, 0x77, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x6e,
	0x74, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x77, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x76, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x77, 0x61, 0x69, 0x74,
	0x69, 0x6e, 0x67, 0x55, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x10, 0x03, 0x12, 0x0e, 0x0a,
	0x0a, 0x75, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x10, 0x04, 0x12, 0x0a, 0x0a,
	0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x05, 0x2a, 0x37, 0x0a, 0x0c, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x74, 0x78, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x10, 0x02, 0x2a, 0x2f, 0x0a, 0x09, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4f, 0x70, 0x73, 0x12,
	0x0b, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x71, 0x75, 0x69, 0x74,
	0x65, 0x10, 0x02, 0x32, 0x81, 0x03, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x61, 0x72, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x54, 0x58, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x54, 0x78, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x54,
	0x78, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x08, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x54, 0x78, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x34, 0x0a, 0x0b, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3c, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x78, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f,
	0x0a, 0x08, 0x4f, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4f, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x4f, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x26, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x12, 0x0b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x63, 0x79, 0x2f, 0x6e,
	0x6f, 0x74, 0x61, 0x72, 0x79, 0x2d, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_notary_service_proto_rawDescOnce sync.Once
	file_proto_notary_service_proto_rawDescData = file_proto_notary_service_proto_rawDesc
)

func file_proto_notary_service_proto_rawDescGZIP() []byte {
	file_proto_notary_service_proto_rawDescOnce.Do(func() {
		file_proto_notary_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_notary_service_proto_rawDescData)
	})
	return file_proto_notary_service_proto_rawDescData
}

var file_proto_notary_service_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_notary_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_notary_service_proto_goTypes = []interface{}{
	(BlockchainTxStatus)(0),                  // 0: proto.BlockchainTxStatus
	(TicketStatus)(0),                        // 1: proto.TicketStatus
	(TicketOps)(0),                           // 2: proto.TicketOps
	(TransferPropertyRequest_NetworkType)(0), // 3: proto.TransferPropertyRequest.NetworkType
	(*Ping)(nil),                             // 4: proto.Ping
	(*Pong)(nil),                             // 5: proto.Pong
	(*Empty)(nil),                            // 6: proto.Empty
	(*CrossTxDetail)(nil),                    // 7: proto.CrossTxDetail
	(*Error)(nil),                            // 8: proto.Error
	(*CreateCrossTxReq)(nil),                 // 9: proto.CreateCrossTxReq
	(*CreateCrossTxResp)(nil),                // 10: proto.CreateCrossTxResp
	(*TransferPropertyRequest)(nil),          // 11: proto.TransferPropertyRequest
	(*TransferPropertyResponse)(nil),         // 12: proto.TransferPropertyResponse
	(*ListTxRequest)(nil),                    // 13: proto.ListTxRequest
	(*EscrowStatus)(nil),                     // 14: proto.EscrowStatus
	(*CrossTxStatus)(nil),                    // 15: proto.CrossTxStatus
	(*CrossTx)(nil),                          // 16: proto.CrossTx
	(*TxIdsInBlock)(nil),                     // 17: proto.TxIdsInBlock
	(*ListTxResponse)(nil),                   // 18: proto.ListTxResponse
	(*QueryTxRequest)(nil),                   // 19: proto.QueryTxRequest
	(*QueryTxResponse)(nil),                  // 20: proto.QueryTxResponse
	(*AdminOpTicketReq)(nil),                 // 21: proto.AdminOpTicketReq
	(*AdminOpTicketResp)(nil),                // 22: proto.AdminOpTicketResp
	(*timestamp.Timestamp)(nil),              // 23: google.protobuf.Timestamp
}
var file_proto_notary_service_proto_depIdxs = []int32{
	7,  // 0: proto.CreateCrossTxReq.detail:type_name -> proto.CrossTxDetail
	8,  // 1: proto.CreateCrossTxResp.error:type_name -> proto.Error
	23, // 2: proto.CreateCrossTxResp.createTime:type_name -> google.protobuf.Timestamp
	3,  // 3: proto.TransferPropertyRequest.networkType:type_name -> proto.TransferPropertyRequest.NetworkType
	8,  // 4: proto.TransferPropertyResponse.error:type_name -> proto.Error
	0,  // 5: proto.EscrowStatus.eStatus:type_name -> proto.BlockchainTxStatus
	0,  // 6: proto.EscrowStatus.fStatus:type_name -> proto.BlockchainTxStatus
	1,  // 7: proto.CrossTxStatus.tStatus:type_name -> proto.TicketStatus
	14, // 8: proto.CrossTxStatus.eStatus:type_name -> proto.EscrowStatus
	7,  // 9: proto.CrossTx.detail:type_name -> proto.CrossTxDetail
	15, // 10: proto.CrossTx.status:type_name -> proto.CrossTxStatus
	23, // 11: proto.CrossTx.createTime:type_name -> google.protobuf.Timestamp
	23, // 12: proto.CrossTx.lastUpdateTime:type_name -> google.protobuf.Timestamp
	8,  // 13: proto.ListTxResponse.error:type_name -> proto.Error
	16, // 14: proto.ListTxResponse.detail:type_name -> proto.CrossTx
	8,  // 15: proto.QueryTxResponse.error:type_name -> proto.Error
	16, // 16: proto.QueryTxResponse.detail:type_name -> proto.CrossTx
	17, // 17: proto.QueryTxResponse.blockchainTxs:type_name -> proto.TxIdsInBlock
	2,  // 18: proto.AdminOpTicketReq.op:type_name -> proto.TicketOps
	8,  // 19: proto.AdminOpTicketResp.err:type_name -> proto.Error
	9,  // 20: proto.NotaryService.CreateCTX:input_type -> proto.CreateCrossTxReq
	11, // 21: proto.NotaryService.SubmitTx:input_type -> proto.TransferPropertyRequest
	6,  // 22: proto.NotaryService.ListTickets:input_type -> proto.Empty
	19, // 23: proto.NotaryService.GetTicket:input_type -> proto.QueryTxRequest
	21, // 24: proto.NotaryService.OpTicket:input_type -> proto.AdminOpTicketReq
	4,  // 25: proto.NotaryService.TestDial:input_type -> proto.Ping
	10, // 26: proto.NotaryService.CreateCTX:output_type -> proto.CreateCrossTxResp
	12, // 27: proto.NotaryService.SubmitTx:output_type -> proto.TransferPropertyResponse
	18, // 28: proto.NotaryService.ListTickets:output_type -> proto.ListTxResponse
	20, // 29: proto.NotaryService.GetTicket:output_type -> proto.QueryTxResponse
	22, // 30: proto.NotaryService.OpTicket:output_type -> proto.AdminOpTicketResp
	5,  // 31: proto.NotaryService.TestDial:output_type -> proto.Pong
	26, // [26:32] is the sub-list for method output_type
	20, // [20:26] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_notary_service_proto_init() }
func file_proto_notary_service_proto_init() {
	if File_proto_notary_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_notary_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrossTxDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCrossTxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCrossTxResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferPropertyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferPropertyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EscrowStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrossTxStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrossTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxIdsInBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryTxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryTxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminOpTicketReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notary_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminOpTicketResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_notary_service_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*CrossTxStatus_TStatus)(nil),
		(*CrossTxStatus_EStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_notary_service_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notary_service_proto_goTypes,
		DependencyIndexes: file_proto_notary_service_proto_depIdxs,
		EnumInfos:         file_proto_notary_service_proto_enumTypes,
		MessageInfos:      file_proto_notary_service_proto_msgTypes,
	}.Build()
	File_proto_notary_service_proto = out.File
	file_proto_notary_service_proto_rawDesc = nil
	file_proto_notary_service_proto_goTypes = nil
	file_proto_notary_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NotaryServiceClient is the client API for NotaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotaryServiceClient interface {
	CreateCTX(ctx context.Context, in *CreateCrossTxReq, opts ...grpc.CallOption) (*CreateCrossTxResp, error)
	SubmitTx(ctx context.Context, opts ...grpc.CallOption) (NotaryService_SubmitTxClient, error)
	ListTickets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTxResponse, error)
	GetTicket(ctx context.Context, in *QueryTxRequest, opts ...grpc.CallOption) (*QueryTxResponse, error)
	OpTicket(ctx context.Context, in *AdminOpTicketReq, opts ...grpc.CallOption) (*AdminOpTicketResp, error)
	TestDial(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
}

type notaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotaryServiceClient(cc grpc.ClientConnInterface) NotaryServiceClient {
	return &notaryServiceClient{cc}
}

func (c *notaryServiceClient) CreateCTX(ctx context.Context, in *CreateCrossTxReq, opts ...grpc.CallOption) (*CreateCrossTxResp, error) {
	out := new(CreateCrossTxResp)
	err := c.cc.Invoke(ctx, "/proto.NotaryService/CreateCTX", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryServiceClient) SubmitTx(ctx context.Context, opts ...grpc.CallOption) (NotaryService_SubmitTxClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NotaryService_serviceDesc.Streams[0], "/proto.NotaryService/SubmitTx", opts...)
	if err != nil {
		return nil, err
	}
	x := &notaryServiceSubmitTxClient{stream}
	return x, nil
}

type NotaryService_SubmitTxClient interface {
	Send(*TransferPropertyRequest) error
	Recv() (*TransferPropertyResponse, error)
	grpc.ClientStream
}

type notaryServiceSubmitTxClient struct {
	grpc.ClientStream
}

func (x *notaryServiceSubmitTxClient) Send(m *TransferPropertyRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *notaryServiceSubmitTxClient) Recv() (*TransferPropertyResponse, error) {
	m := new(TransferPropertyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *notaryServiceClient) ListTickets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTxResponse, error) {
	out := new(ListTxResponse)
	err := c.cc.Invoke(ctx, "/proto.NotaryService/ListTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryServiceClient) GetTicket(ctx context.Context, in *QueryTxRequest, opts ...grpc.CallOption) (*QueryTxResponse, error) {
	out := new(QueryTxResponse)
	err := c.cc.Invoke(ctx, "/proto.NotaryService/GetTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryServiceClient) OpTicket(ctx context.Context, in *AdminOpTicketReq, opts ...grpc.CallOption) (*AdminOpTicketResp, error) {
	out := new(AdminOpTicketResp)
	err := c.cc.Invoke(ctx, "/proto.NotaryService/OpTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryServiceClient) TestDial(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/proto.NotaryService/TestDial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotaryServiceServer is the server API for NotaryService service.
type NotaryServiceServer interface {
	CreateCTX(context.Context, *CreateCrossTxReq) (*CreateCrossTxResp, error)
	SubmitTx(NotaryService_SubmitTxServer) error
	ListTickets(context.Context, *Empty) (*ListTxResponse, error)
	GetTicket(context.Context, *QueryTxRequest) (*QueryTxResponse, error)
	OpTicket(context.Context, *AdminOpTicketReq) (*AdminOpTicketResp, error)
	TestDial(context.Context, *Ping) (*Pong, error)
}

// UnimplementedNotaryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNotaryServiceServer struct {
}

func (*UnimplementedNotaryServiceServer) CreateCTX(context.Context, *CreateCrossTxReq) (*CreateCrossTxResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCTX not implemented")
}
func (*UnimplementedNotaryServiceServer) SubmitTx(NotaryService_SubmitTxServer) error {
	return status.Errorf(codes.Unimplemented, "method SubmitTx not implemented")
}
func (*UnimplementedNotaryServiceServer) ListTickets(context.Context, *Empty) (*ListTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTickets not implemented")
}
func (*UnimplementedNotaryServiceServer) GetTicket(context.Context, *QueryTxRequest) (*QueryTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTicket not implemented")
}
func (*UnimplementedNotaryServiceServer) OpTicket(context.Context, *AdminOpTicketReq) (*AdminOpTicketResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpTicket not implemented")
}
func (*UnimplementedNotaryServiceServer) TestDial(context.Context, *Ping) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestDial not implemented")
}

func RegisterNotaryServiceServer(s *grpc.Server, srv NotaryServiceServer) {
	s.RegisterService(&_NotaryService_serviceDesc, srv)
}

func _NotaryService_CreateCTX_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCrossTxReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServiceServer).CreateCTX(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NotaryService/CreateCTX",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServiceServer).CreateCTX(ctx, req.(*CreateCrossTxReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotaryService_SubmitTx_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NotaryServiceServer).SubmitTx(&notaryServiceSubmitTxServer{stream})
}

type NotaryService_SubmitTxServer interface {
	Send(*TransferPropertyResponse) error
	Recv() (*TransferPropertyRequest, error)
	grpc.ServerStream
}

type notaryServiceSubmitTxServer struct {
	grpc.ServerStream
}

func (x *notaryServiceSubmitTxServer) Send(m *TransferPropertyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *notaryServiceSubmitTxServer) Recv() (*TransferPropertyRequest, error) {
	m := new(TransferPropertyRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _NotaryService_ListTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServiceServer).ListTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NotaryService/ListTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServiceServer).ListTickets(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotaryService_GetTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServiceServer).GetTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NotaryService/GetTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServiceServer).GetTicket(ctx, req.(*QueryTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotaryService_OpTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminOpTicketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServiceServer).OpTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NotaryService/OpTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServiceServer).OpTicket(ctx, req.(*AdminOpTicketReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotaryService_TestDial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServiceServer).TestDial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NotaryService/TestDial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServiceServer).TestDial(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotaryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NotaryService",
	HandlerType: (*NotaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCTX",
			Handler:    _NotaryService_CreateCTX_Handler,
		},
		{
			MethodName: "ListTickets",
			Handler:    _NotaryService_ListTickets_Handler,
		},
		{
			MethodName: "GetTicket",
			Handler:    _NotaryService_GetTicket_Handler,
		},
		{
			MethodName: "OpTicket",
			Handler:    _NotaryService_OpTicket_Handler,
		},
		{
			MethodName: "TestDial",
			Handler:    _NotaryService_TestDial_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubmitTx",
			Handler:       _NotaryService_SubmitTx_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/notary_service.proto",
}
